name: Build Asterisk PBX

on:
  workflow_call:
    inputs:
      releases:
        required: true
        type: string

jobs:
  build-asterisk:
    name: Build Asterisk PBX
    runs-on: ubuntu-20.04
    timeout-minutes: 600
    strategy:
      max-parallel: 64
      fail-fast: false
      matrix: ${{ fromJson(inputs.releases) }}

    steps:
      - uses: actions/checkout@v3

      - name: Create docker buildx instance
        id: buildx
        shell: bash
        run: |
          set -ueox pipefail
          echo "::set-output name=value::$(docker buildx create)"

      - name: Build Astersik PBX
        shell: bash
        run: |
          set -ueox pipefail

          RELEASE="${{ matrix.run }}"

          if [[ "$RELEASE" =~ ^1\.2\. ]]; then
            DEBIAN_RELEASE="jessie-slim"
            ASTERISK_VERSION="1.2.40"
            ASTERISK_ADDONS_VERSION="1.2.9"
            echo "Building Asterisk PBX $RELEASE"
          elif [[ "$RELEASE" =~ ^1\.4\. ]]; then
            DEBIAN_RELEASE="jessie-slim"
            ASTERISK_VERSION="1.4.44"
            ASTERISK_ADDONS_VERSION="1.4.13"
            echo "Building Asterisk PBX $RELEASE"
          elif [[ "$RELEASE" =~ ^1\.6\. ]]; then
            DEBIAN_RELEASE="jessie-slim"
            ASTERISK_VERSION="1.6.2.24"
            ASTERISK_ADDONS_VERSION="1.6.2.4"
            echo "Building Asterisk PBX $RELEASE"
          elif [[ "$RELEASE" =~ ^1\.8\. ]]; then
            DEBIAN_RELEASE="jessie-slim"
            ASTERISK_VERSION="1.8.32.3"
            echo "Building Asterisk PBX $RELEASE"
          elif [[ "$RELEASE" =~ ^10\. ]]; then
            echo "Building Asterisk PBX $RELEASE"
          elif [[ "$RELEASE" =~ ^11\. ]]; then
            echo "Building Asterisk PBX $RELEASE"
          elif [[ "$RELEASE" =~ ^12\. ]]; then
            echo "Building Asterisk PBX $RELEASE"
          elif [[ "$RELEASE" =~ ^13\. ]]; then
            echo "Building Asterisk PBX $RELEASE"
          elif [[ "$RELEASE" =~ ^14\. ]]; then
            echo "Building Asterisk PBX $RELEASE"
          elif [[ "$RELEASE" =~ ^15\. ]]; then
            echo "Building Asterisk PBX $RELEASE"
          elif [[ "$RELEASE" =~ ^16(\.|-). ]]; then
            echo "Building Asterisk PBX $RELEASE"
          elif [[ "$RELEASE" =~ ^17(\.|-). ]]; then
            echo "Building Asterisk PBX $RELEASE"
          elif [[ "$RELEASE" =~ ^18(\.|-). ]]; then
            echo "Building Asterisk PBX $RELEASE"
          elif [[ "$RELEASE" =~ ^19(\.|-). ]]; then
            echo "Building Asterisk PBX $RELEASE"
          else
            echo "Unsupported release"
            exit 1
          fi

      - name: Remove docker buildx instance
        if: ${{ always() }}
        shell: bash
        run: |
          BUILDX="${{ steps.buildx.outputs.value }}"
          [ "${BUILDX}" != "" ] && docker buildx rm "${BUILDX}"
