name: Build Alpine-based Asterisk images

on:
  workflow_call:
    inputs:
      docker-tags:
        required: true
        type: string

jobs:
  build-images:
    name: Build Alpine-based Asterisk images
    runs-on: ubuntu-latest
    timeout-minutes: 600
    strategy:
      max-parallel: 64
      fail-fast: false
      matrix: ${{ fromJson(inputs.docker-tags) }}

    steps:
      - uses: actions/checkout@v3

      - name: Create docker buildx instance
        id: buildx
        shell: bash
        run: |
          set -ueox pipefail
          echo "::set-output name=value::$(docker buildx create)"

      - name: Generate docker image
        shell: bash
        run: |
          set -ueox pipefail

          TAG="${{ matrix.run }}"

      - name: Remove docker buildx instance
        if: ${{ always() }}
        shell: bash
        run: |
          BUILDX="${{ steps.buildx.outputs.value }}"
          [ "${BUILDX}" != "" ] && docker buildx rm "${BUILDX}"
