name: Process new Asterisk releases

on:
  workflow_dispatch:

  push:
    paths:
      - .github/workflows/process-asterisk-releases.yml
      - 'asterisk-releases.txt'

jobs:
  releases:
    name: Discover new Asterisk releases
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
       matrix: ${{ steps.releases.outputs.matrix }}

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set dynamic matrix
        id: releases
        shell: bash
        run: |
          set -ueox pipefail

          set +e
          BUILD_RELEASES="$(
            git log -p -1 ./asterisk-releases.txt \
            | grep -P '^\+\d+' \
            | sed -re 's/^\+//g'
          )"
          set -e

          # JSON_MATRIX="{\"include\":[{\"run\":\"run1\"},{\"run\":\"run2\"}]}"
          # echo "::set-output name=matrix::${JSON_MATRIX}"

          if [ "$BUILD_RELEASES" != "" ]; then
            JSON_MATRIX="$(
              echo -n "$BUILD_RELEASES" \
              | tr '\n' ' ' \
              | jq --slurp -c -R 'split(" ") | map({run: .}) | {include: .}'
            )"
          else
            JSON_MATRIX=""
          fi

          echo "::set-output name=matrix::${JSON_MATRIX}"

          echo "Continue to build following Asterisk PBX releases:"
          echo "=================================================="
          echo -e "$BUILD_RELEASES"
          echo
          echo
          echo "JSON payload:"
          echo "=================================================="
          echo "$JSON_MATRIX" | jq

  build:
    needs: releases
    if: ${{ needs.releases.outputs.matrix != '' }}
    uses: ./.github/workflows/build-asterisk.yml
    with:
      releases: ${{ needs.releases.outputs.matrix }}
